version: '3.8'

services:
  # MySQL データベース
  mysql:
    image: docker.io/mysql:8.0
    container_name: lazychillroom_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lazychillroom
      MYSQL_USER: lazychillroom_user
      MYSQL_PASSWORD: lazychillroom_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # SQLファイルによる自動初期化は無効化（PHPスクリプトで初期化）
      # - ./sql:/docker-entrypoint-initdb.d
    networks:
      - lazychillroom_network

  # PHP + Apache ウェブサーバー
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lazychillroom_web:latest
    container_name: lazychillroom_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=lazychillroom
      - DB_USER=lazychillroom_user
      - DB_PASSWORD=lazychillroom_password
      - DB_ROOT_PASSWORD=rootpassword
    depends_on:
      - mysql
    networks:
      - lazychillroom_network

  # phpMyAdmin データベース管理
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    container_name: lazychillroom_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - lazychillroom_network

volumes:
  mysql_data:
    driver: local

networks:
  lazychillroom_network:
    driver: bridge